// Install only this version in Assets/DesertTemple/Editor/.
using UnityEngine;
using UnityEditor;
using System.IO;

public static class DesertTemplePrefabBuilder
{
    [MenuItem("Tools/Desert Tower/Create Desert Temple Prefab")]
    public static void Build()
    {
        string path = AssetDatabase.GetAssetPath(Selection.activeObject);
        if (Path.GetFileNameWithoutExtension(path) != "DesertTemple_Visual")
        {
            EditorUtility.DisplayDialog("Desert Temple", "Select the new DesertTemple_Visual.fbx in the Project window first.", "OK");
            return;
        }
        string folder = Path.GetDirectoryName(path).Replace('\\', '/');
        string collisionPath = folder + "/DesertTemple_Collision.fbx";
        var collisionAsset = AssetDatabase.LoadAssetAtPath<GameObject>(collisionPath);
        if (collisionAsset == null)
        {
            EditorUtility.DisplayDialog("Desert Temple", "Place the matching V6 collision FBX beside the visual FBX.", "OK");
            return;
        }
        var filters = collisionAsset.GetComponentsInChildren<MeshFilter>(true);
        if (filters.Length != 1 || filters[0].sharedMesh == null)
        {
            EditorUtility.DisplayDialog("Desert Temple", "This builder requires the V6 single-mesh collision file. Check the imported FBX version.", "OK");
            return;
        }
        var root = new GameObject("DesertTemple_V6");
        try
        {
            var visible = (GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>(path));
            visible.transform.SetParent(root.transform, false);
            var physical = (GameObject)PrefabUtility.InstantiatePrefab(collisionAsset);
            physical.transform.SetParent(root.transform, false);
            // Remove any colliders automatically generated by FBX import settings.
            foreach (var existing in root.GetComponentsInChildren<Collider>(true)) Object.DestroyImmediate(existing);
            foreach (var renderer in physical.GetComponentsInChildren<Renderer>(true)) renderer.enabled = false;
            var filter = physical.GetComponentInChildren<MeshFilter>(true);
            var collider = filter.gameObject.AddComponent<MeshCollider>();
            collider.convex = false;
            collider.sharedMesh = filter.sharedMesh;
            foreach (var transform in root.GetComponentsInChildren<Transform>(true)) transform.gameObject.isStatic = true;
            string output = AssetDatabase.GenerateUniqueAssetPath(folder + "/DesertTemple_V6.prefab");
            PrefabUtility.SaveAsPrefabAsset(root, output);
            Selection.activeObject = AssetDatabase.LoadAssetAtPath<GameObject>(output);
            EditorGUIUtility.PingObject(Selection.activeObject);
            Debug.Log("Created " + output + " with exactly one static MeshCollider. Disable the old scene model before placing this prefab.");
        }
        finally { Object.DestroyImmediate(root); }
    }
}
